### ISSUE TITLE
overscanRowCount scroll down bug

### ISSUE THREAD

**Issue by pandanax** [bvaughn/react-window#394] opened 2019-12-24 08:35 UTC
i've set overscanRowCount to 30 but item disappears when scrolling down (when it start is outside the screen). When scrolling up or scrolling stopped everything is fine.

Here is example. I've set item height more than 1 row to make it visible.

![bug1](https://user-images.githubusercontent.com/6092915/71403584-3c9eef00-2641-11ea-977c-696b4e86a62b.gif)

**Comment by pandanax** [comment] 2019-12-24 08:46
Look, when scroll up, row index starts from zero, when scroll down, row index starts form 3-6.
![bug2](https://user-images.githubusercontent.com/6092915/71404122-c13e3d00-2642-11ea-89fb-7d2d5aa35891.gif)

**Comment by bvaughn** [comment] 2019-12-25 02:18
> Look, when scroll up, row index starts from zero, when scroll down, row index starts form 3-6.

That is expected. This library only pre-renders in the direction being scrolled. Pre-rendering in the opposite direction would generally be unnecessary work.

As for the rest of this, you'll need to provide a repro case on Code Sandbox. Without a runnable repro case, I'm not even going to speculate.

**Comment by pandanax** [comment] 2019-12-25 07:06
Hey! I've made repro example here:
https://codesandbox.io/s/patient-cloud-jnifm?from-embed

**Comment by bvaughn** [comment] 2019-12-25 14:35
The repro says:
> Watch to second column and scroll up and down.

What am I watching for?

The row in the middle disappears after a bit, but that's because you're using a fixed height grid and you've told it the row heights are 35 pixels tall. The grid component hides it once it's scrolled off the viewport. This seems to be working as designed.

**Comment by pandanax** [comment] 2019-12-25 14:58
i expected same behavior independently scrolling direction. i expected overscan param will keep rows rendered when scrolling. Seems i was wrong with my expectations. Sorry.

**Comment by bvaughn** [comment] 2019-12-25 15:03
Please, don't feel the need to apologize for expectations :smile:

As I mentioned in my initial replace- this library only pre-renders in the direction being scrolled. Pre-rendering in the opposite direction would generally be unnecessary work. The one exception is that I *do* over render *one* row/column in the other direction, for accessibility purposes (so you can tab/shift+tab to it).

The tests for this might provide a little more insight into the behavior I expect:
https://github.com/bvaughn/react-window/blob/921dbb37aa42750509d7839014510dea2c7014ac/src/__tests__/FixedSizeList.js#L283-L345

Although you'd have to cross-reference the [snapshot file](https://github.com/bvaughn/react-window/blob/921dbb37aa42750509d7839014510dea2c7014ac/src/__tests__/__snapshots__/FixedSizeList.js.snap) which is a bit of work ☹️ 

Maybe I should make this more explicit in the documentation. Although in many ways, I don't want people to *have* to thin too much about overscan behavior.

Anyway, all of this to say- this looks like the behavior I expect/intend, so I think we can close this issue? Unless this is actually causes a problem in some way, in which case let's talk about how?

**Comment by pandanax** [comment] 2019-12-26 07:57
i have a Grid. The first column of grid is a scale. The scale contains items with height **H** (each item has same height). All other columns contain items which can start from **X*H** and has **Y*H** height (**X** and **Y** is any int). It is very similar with fixed height grid but i have one problem. "Tall" items disappear, i didn't see theirs bottom when theirs top is outside the screen. 

Something like that:
<img width="1678" alt="Screenshot 2019-12-26 at 10 56 11" src="https://user-images.githubusercontent.com/6092915/71465726-6df8f580-27ce-11ea-9160-afc96f640637.png">

Could you advise how to make it better?

**Comment by bvaughn** [comment] 2019-12-26 12:40
What you're describing is not supported by react-window. Every column in a
grid row must have the same height.

**Comment by bvaughn** [comment] 2019-12-26 12:41
I'm going to close this issue now since it seems to be a combination of a misunderstand and an unsupported use case. We can keep talking on this issue though.

**Closed by bvaughn** 2019-12-26 12:41 UTC
Labels: 👀 needs info
