### ISSUE TITLE
Cannot scroll to List bottom if there is a horizontal scrollbar

### ISSUE THREAD

**Issue by Saulukass** [bvaughn/react-window#383] opened 2019-11-21 15:00 UTC
Seems like there is a problem with scrolling to the vertical list bottom. It is impossible to reach the list end if there is a horizontal scrollbar.

[Example](https://codesandbox.io/s/react-window-scroll-z86vn)

It looks like when scrolling to the end, wide row is removed and horizontal scroll bar disappears. That causes wide row to be added again. As a result this causes horizontal scroll bar to reappear and vertical scrollbar move up a little bit. 

On Chrome this leads to bouncing at the end of list. 
On Firefox bouncing does not reproduce, but last row is always covered by horizontal scrollbar. 

This also reproduces with VariableSizeList.

**Comment by bvaughn** [comment] 2019-12-28 18:12
I can't reproduce what you're describing Chrome, whether there's a wide item or not, so I'm going to close this issue. If you provide a different repro (or better instructions) that reproduces the issue you're reporting, I'll re-open it!

**Closed by bvaughn** 2019-12-28 18:12 UTC
