### ISSUE TITLE
Adding data to DynamicSizeList results in a height calculation error

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-window#340] opened 2019-09-30 03:02 UTC
![image](https://user-images.githubusercontent.com/47209029/65846832-ae80d880-e371-11e9-9952-184201157a62.png)

The data for the style is incorrect after adding the data

**Comment by JinJieTan** [comment] 2019-09-30 03:03
Two consecutive tops have the same value, and the last one is zero

**Comment by bvaughn** [comment] 2019-09-30 15:42
You seem like a nice person, and I hope this doesn't seem rude- but I'm going to say the same thing I said on #339 (and other previous issues you opened).

Screenshots of the elements panel are not sufficient for me (or anyone) to help answer a question or investigate a potential bug. **I need a full code example** to be provided when asking a question, or I'm not going to make the time to look at it. **I'm going to close this issue because it has very little actual info.**

I'll also add that `DynamicSizeList` hasn't been released yet because I know it's not quite ready- so bug reports **are** helpful, but only if they provide enough context for me to actually reproduce and understand them.

**Closed by bvaughn** 2019-09-30 15:42 UTC

**Comment by JinJieTan** [comment] 2019-10-16 03:35
Dear,bvaughn


Using virtual list，If the list length is constantly increasing in large quantities, will the memory leak?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Brian Vaughn"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月30日(星期一) 晚上11:42
收件人:&nbsp;"bvaughn/react-window"<react-window@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bvaughn/react-window] Adding data to DynamicSizeList results in a height calculation error (#340)




You seem like a nice person, and I hope this doesn't seem rude- but I'm going to say the same thing I said on #339 (and other previous issues you opened).
 
Screenshots of the elements panel are not sufficient for me (or anyone) to help answer a question or investigate a potential bug. I need a full code example to be provided when asking a question, or I'm not going to make the time to look at it. I'm going to close this issue because it has very little actual info.
 
I'll also add that DynamicSizeList hasn't been released yet because I know it's not quite ready- so bug reports are helpful, but only if they provide enough context for me to actually reproduce and understand them.
