### ISSUE TITLE
In the mobile browser, it will shake when scrolling to the top or bottom.

### ISSUE THREAD

**Issue by chenhebing** [bvaughn/react-window#244] opened 2019-05-20 07:42 UTC
Such as the title, list will shake when scrolling to the top or bottom, but react-virtualized is not happened.

You can view the video below.

[video url](https://youtu.be/HJd70gdAzFs)

**Comment by bvaughn** [comment] 2019-05-20 14:59
This looks like Safari elastic scrolling and not something this library in particular is doing.

**Comment by blenoski** [comment] 2019-05-22 15:53
I am observing similar behavior on Safari iOS (not seeing in Chrome iOS).  FWIW, found a commit from react-virtualized that seems like it was related to this problem: https://github.com/bvaughn/react-virtualized/pull/616/files

**Comment by bvaughn** [comment] 2019-05-22 15:58
Want to try that out in react-window @blenoski ?

**Comment by blenoski** [comment] 2019-05-22 20:29
@bvaughn 
I will give it a try and report back to the issue.

I also have to update my comment 2 back, I was able to reproduce on Chrome iOS.  Attaching a screen capture from iPhone7 for reference:
![ios_scroll_bounce_issue](https://user-images.githubusercontent.com/26208242/58206511-67d5f000-7ca6-11e9-9206-ea83931eb3d2.gif)

**Comment by bvaughn** [comment] 2019-05-22 20:35
Cool, thanks! 😁

**Comment by blenoski** [comment] 2019-05-22 23:10
Update:
I did some quick hacking and was able to confirm that clamping scrollTop to [0, totalHeight] eliminates the observed flickering on iOS (this was in the _onScrollVertical function in createListComponent.js

It does require knowing the current height of the innerContainer element plus the height of the last row which I imagine will be the tricky part.  Also, assuming similar issues would exist for horizontal scrolling but have not yet been able to reproduce the flickering there.

Anyhow, going to pull down the repo and dig into the code a little to see if I can figure this out :)

**Comment by blenoski** [comment] 2019-05-23 15:50
Update (cc. @bvaughn)

Have a PR up here (https://github.com/bvaughn/react-window/pull/250).
Scoped the PR to just vertical scrolling on lists but I was able to verify it removes the issue shown in the GIF three posts back.

**Comment by EyMaddis** [comment] 2019-05-27 09:48
I just noticed the same. This issue is basically this old [react-virtualized](https://github.com/bvaughn/react-virtualized/issues/532) issue.

**Comment by bvaughn** [comment] 2019-05-27 17:36
Worth noting that the linked RV commit was reverted in https://github.com/bvaughn/react-virtualized/pull/616 so the long-standing RV solution to this is just to prevent scroll offsets less than 0. I think I'm comfortable making that change to RW as well, although I'll need to make sure it doesn't break RTL.

**Comment by bvaughn** [comment] 2019-05-28 00:25
Bug fix released in 1.8.2 - https://github.com/bvaughn/react-window/blob/master/CHANGELOG.md#182

**Closed by bvaughn** 2019-05-28 00:25 UTC
