### ISSUE TITLE
When I use ref. Current. ScrolltoItem (0), the screen goes blank

### ISSUE THREAD

**Issue by JinJieTan** [bvaughn/react-window#320] opened 2019-09-04 04:31 UTC
When I use ref. Current. ScrolltoItem (0), the screen goes blank

In the above case, only my scroll bar will be white when I call this method at 0. Can I get the current scroll position

And then I scroll and there's the content again

**Comment by bvaughn** [comment] 2019-09-04 14:47
This issue isn't actionable, since it doesn't have enough info for me to reproduce (or even see) what you're reporting. Because of this, I'm going to close it. If you provide a repro, I'll re-open and take a look.

You can fork [this Code Sandbox](https://codesandbox.io/s/github/bvaughn/react-window/tree/master/website/sandboxes/scrolling-to-a-list-item) to start, if you'd like.

**Closed by bvaughn** 2019-09-04 14:47 UTC

**Comment by JinJieTan** [comment] 2019-09-04 14:53
```
<List
                    className="list"
                    height={536}
                    itemCount={list.length}
                    itemSize={68}
                    ref={this.ref}
                    width={260}
                    itemData={{
                      list,
                      userId,
                      message,
                      saveChatItemData: this.saveChatItemData,
                      history,
                      getInfo: this.getInfo,
                      contactList,
                      groupList,
                    }}
                  >
                    {Row}
                  </List>
```

This is my code, when I scroll bar at the top, use this. Ref. Current. ScrollToItem (0); The list of elements disappears, and the contents appear again when I scroll

**Comment by bvaughn** [comment] 2019-09-04 14:56
That is not sufficient to repro the issue you describe. It doesn't even include your item renderer source (the `Row` component).

I linked to a Code Sandbox that you could fork and reproduce the problem you're describing. Or you could perhaps somehow share your actual app/code with me.

I can't speculate what might be going wrong when I only have a small partial snippet.

**Comment by JinJieTan** [comment] 2019-09-04 14:56
It starts out like this 
![image](https://user-images.githubusercontent.com/47209029/64266369-1573c300-cf67-11e9-98f8-ddc0c2468bee.png)

When I call this.ref.current.scrolltoitem (0),

![image](https://user-images.githubusercontent.com/47209029/64266453-350aeb80-cf67-11e9-8cc0-465e9d05f0c2.png)

Then scroll the mouse and the content appears again

![image](https://user-images.githubusercontent.com/47209029/64266493-3f2cea00-cf67-11e9-956d-76d4f12a47cf.png)

**Comment by JinJieTan** [comment] 2019-09-04 14:57
Row component  code: 

```
class Row extends React.PureComponent {
  render() {
    const { index, style, data } = this.props;
    const { contactList, groupList, list, userId, message, saveChatItemData, history, getInfo } = data;
    const infoList = getInfo(
      list[index].historyType === 1 ? contactList.list : groupList.list,
      list[index].historyId,
      list[index].historyType,
    );
    return (
      <ChatItem
        key={list[index].historyId}
        item={list[index]}
        info={infoList}
        userId={userId}
        message={message}
        onClick={saveChatItemData.bind(this, list[index].historyId, list[index].historyType)}
        id={history}
        style={style}
      />
    );
  }
}
```

**Comment by JinJieTan** [comment] 2019-09-04 15:01
As long as it's not a scroll bar at the top state called when this. Ref. Current. Scrolltoitem (0), there are no problems

**Comment by bvaughn** [comment] 2019-09-04 15:04
**Unless you can point me at some code where I can run and see this happening- I'm not going to be able to trouble shoot this.**

Although I will say, make sure the `style` you're passing to `ChatItem` is actually being used and attached to a DOM node.

**Comment by JinJieTan** [comment] 2019-09-04 15:04
Or is there an API to get the current scroll bar ？

**Comment by JinJieTan** [comment] 2019-09-04 15:11
Ok, so can I have an API to determine the current position of the scroll bar? It might not work if it was given to you

**Comment by nihgwu** [comment] 2019-09-04 15:16
@JinJieTan what @bvaughn want to emphasize here is to create a reproducible repo he can debug with, there is impossible with only works and snippets, please stop your one-man show, with a reproducible repo it's easy to determine it's a bug from react-window of your own code

BTW you can get the scroll position via `onScroll` callback, but I don't think that would be helpful, I guess you just forget to pass `style` to the dom element in `ChatItem`, BUT, a reproducible repo would tell us everything

**Comment by JinJieTan** [comment] 2019-09-04 15:23
The list of elements when I have a problem looks like this
![image](https://user-images.githubusercontent.com/47209029/64268243-4ef9fd80-cf6a-11e9-857b-783d7d182c66.png)


It's normal
![image](https://user-images.githubusercontent.com/47209029/64268463-b87a0c00-cf6a-11e9-8343-51cfed017236.png)

My inner elements are cleared

If you think my reason is that style didn't come in, then I don't think so.

Every time I send a message, I need to scroll to the top, and when only my initial state of the scroll bar is at the top, the call this.ref.current.scrolltoitem (0) will have a problem, otherwise it will be the following, normal state


![image](https://user-images.githubusercontent.com/47209029/64268463-b87a0c00-cf6a-11e9-8343-51cfed017236.png)

And then normal
![image](https://user-images.githubusercontent.com/47209029/64268477-c039b080-cf6a-11e9-8bb0-3c1c57edc8f5.png)

**Comment by JinJieTan** [comment] 2019-09-04 15:26
![image](https://user-images.githubusercontent.com/47209029/64268811-5f5ea800-cf6b-11e9-85a7-283eed68ee15.png)

normal 

![image](https://user-images.githubusercontent.com/47209029/64268840-6c7b9700-cf6b-11e9-931b-bd660bbb0eff.png)

**Comment by bvaughn** [comment] 2019-09-04 15:29
I've asked for a repro a few times, and it seems like that request is being ignored in favor of a barrage of screenshots and stuff. I don't assume bad intent here, maybe still a misunderstanding, but I have other things to do as well and getting email notifications every 5 minutes is pretty distracting. I'm sorry, but I think I'm going to have to mute this thread.

**Comment by nihgwu** [comment] 2019-09-04 15:30
Instead of wasting time on screenshooting, why not just working on a simple repo?

**Comment by JinJieTan** [comment] 2019-09-04 15:35
I am really sorry. Maybe I have been troubled by this problem for too long. I will prepare a code before submitting it.

发自我的iPhone


------------------ Original ------------------

**Comment by JinJieTan** [comment] 2019-09-05 02:07
I added a variable lock in the mouse scroll event, and did not scroll to the top if the scrollbar offset was 0，I'm very sorry ，Thank you for being so concerned about my problems. I like your library very much
