### ISSUE TITLE
Unable to start local development server

### ISSUE THREAD

**Issue by ivancuric** [bvaughn/react-window#64] opened 2018-10-02 11:44 UTC
I was following the instructions from https://github.com/bvaughn/react-window/blob/master/website/README.md

However, I'm getting an error message when starting the dev server for the website:
```
Error: Cannot find module 'react-dev-utils/workspaceUtils'
```

**Comment by ivancuric** [comment] 2018-10-03 09:16
yep

**Comment by bvaughn** [comment] 2018-10-03 14:02
Sorry. Not sure how to help with this size I'm not able to repo (and I've tried a couple of different laptops recently with new setups.)

**Comment by bvaughn** [comment] 2018-10-03 14:36
Just tried another fresh install with Node v8.4.0:
```js
git clone git@github.com:bvaughn/react-window.git
cd ./react-window
yarn install
cd ./website
yarn install
cd ../
yarn website:run
```
And it worked fine for me. I didn't do the "link" step but I don't think that would be related to what you're describing.

Can you try running that exact sequence and telling me if it still fails?

Even if it does, I don't think there's much I can do to help.

**Comment by bvaughn** [comment] 2018-10-03 18:17
Let's keep working through this together, but I'm going to close the issue for now. 👍

**Closed by bvaughn** 2018-10-03 18:17 UTC

**Comment by ivancuric** [comment] 2018-10-12 09:11
Hey no probs. 
It works when I don't link the lib. When I do tho:
```shell
❯ yarn website:run
yarn run v1.10.1
$ cd website && yarn start
$ node scripts/start.js
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'react-dev-utils/workspaceUtils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/ivan/Dev/react-window/website/config/paths.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

These are the steps I've done:
`react-window > yarn install`
`react-window > yarn link`
`react-window/website > yarn link "react-window"`
`react-window/website > yarn install`
`react-window > yarn start` < runs
`react-window/website > yarn start` < breaks

**Comment by bvaughn** [comment] 2018-10-12 09:16
Hm. Interesting.

Looks like `react-dev-utils` has gotten a stable release since I ejected. Try the following and let me know if it makes any difference?

```
react-window/website > yarn add react-dev-utils
react-window/website > yarn start
```

**Comment by ivancuric** [comment] 2018-10-12 09:18
Tried that. No luck.

**Comment by ivancuric** [comment] 2018-10-12 09:36
Ok. Gonna make a PR anyway :D

**Comment by bvaughn** [comment] 2018-10-12 09:39
If `npm link` is the part that breaks for you, you should still be able to test your changes by just installing the (static) build:
```
react-window/website > yarn add ../
react-window/website > yarn start
```
The only thing this won't do that `npm link` will is pick up on changes made to `react-window`. (You would need to run `yarn add` again.)

**Comment by bvaughn** [comment] 2018-10-15 07:48
Looks like the problem is caused by [this line](https://github.com/bvaughn/react-window/blob/5ebe8707d86316a5139ddfd9184cc2b50e4933d5/website/config/paths.js#L4). Pretty sure we don't even need that line, with the way the repo is structured.

**Comment by bvaughn** [comment] 2018-10-15 08:04
facebook/create-react-app/issues/5437

**Comment by bvaughn** [comment] 2018-10-15 08:14
I believe I've pushed a fix fort his to master with a58b808

**Comment by somi92** [comment] 2018-11-25 14:52
Hello,

I'm having issues to start development server on my machine (Windows 10, Node v10.13.0).

I've cloned my fork and:

```
cd ./react-window
yarn install
cd ./website
yarn install
cd ../
yarn website:run
```

The error is:

```
Failed to compile.

./src/routes/examples/FixedSizeList.js
121:11-26 "export 'default' (imported as 'CODE_HORIZONTAL') was not found in '..
/../code/FixedSizeListHorizontal.js'
```

I get this 'export default' error for all example components in relation to code directory. I've gone trough example code and tried to comment out these `<CodeBlock value={...} />` parts just to get things running but finally I get:

```
Failed to compile.

../dist/index.esm.js
Module not found: Can't resolve './FixedSizeGrid.js' in 'react-window\dist'
```

**Comment by bvaughn** [comment] 2018-11-25 16:34
I'm sorry to hear that, @somi92. If you're able to work through it, I'd welcome PRs that update docs or configuration to improve the process for other Windows users. I won't be able to look into it myself because of limitated time (and I'm not a Windows user).

**Comment by somi92** [comment] 2018-11-25 19:42
I've managed to get it to work by using [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10). But I'm still curios why it doesn't work in Windows alone. I'll get back if I find out more.
