### ISSUE TITLE
Increase scroll windows

### ISSUE THREAD

**Issue by Domino987** [bvaughn/react-window#412] opened 2020-02-03 21:25 UTC
Hi, great lib but I was wondering, if it is possible to scroll the window, if somewhere on the screen is scrolled.
I have only one window on my screen and my user want to be able to scroll it, where ever they scroll, e.g. sidebar. I was wondering if that is possible.

I tried to check on wheel event, but I cannot scroll by pixel but only by index, which does not work.

Does anybody has an idea?

**Comment by bvaughn** [comment] 2020-02-03 21:41
This is not supported.

Duplicate of:
* #30
* #135
* #192
* #193
* #224

**Closed by bvaughn** 2020-02-03 21:41 UTC
