### ISSUE TITLE
Jumps to top of list when scrollbar dragged past bottom

### ISSUE THREAD

**Issue by rssfrncs** [bvaughn/react-window#96] opened 2018-12-03 08:21 UTC
It's a bit tricky to explain i'll do my best!

Browser - Tested only in Chrome (70.0.3538.110).

Example - https://codesandbox.io/s/k2lpl9m0l3

Method - Ensure the scrollbar is not fully scrolled to the bottom of the list (variable or fixed). Next start to drag the scrollbar down, once your mouse cursor gets past the end of the list (at around +30px see below screenshot for rough estimate of where it triggers) the list jumps to the top.

![image](https://user-images.githubusercontent.com/7808978/49361782-b1b92280-f6d4-11e8-9e21-167d28e55a69.png)

**Comment by bvaughn** [comment] 2018-12-03 22:35
I can't reproduce this issue using Chrome 70.0.3538.77 on macOS 10.13.6 (with "Show scroll bars: Always")

Any chance I can get a recording from you?

Any chance you could add logging to your version of react-window (inside of `node_modules`) to print what the `scrollTop` values are [here](https://github.com/bvaughn/react-window/blob/94de9a75a379cb07a7e51435597bc8afba28a07a/src/createListComponent.js#L471)?

**Comment by JeffBaumgardt** [comment] 2018-12-03 22:43
On Windows 10 I've confirmed the above behavior. I don't have an clues as to the cause as of yet
System: Windows 10
Chrome: 70.0.3538.110

**Comment by ghurlman** [comment] 2018-12-03 22:43
Repros in Chrome 70.0.3538.110 on Windows 10
Does not repro in Firefox Dev Edition, 64.0b13.

**Comment by bvaughn** [comment] 2018-12-03 22:56
Probably unsurprisingly, this seems to be Windows behavior (rather than specific to react-window):
http://www.tomshardware.com/answers/id-3663415/stop-scrollbar-jumps-top-behaviour.html

That doesn't mean I shouldn't work around it, just that it seems to be common-ish?

**Comment by mattlacey** [comment] 2018-12-03 22:59
Confirmed in Opera Version:56.0.3051.104

![capture](https://user-images.githubusercontent.com/1256283/49406972-37a79d00-f7ab-11e8-8533-423307e845c4.gif)

But as @bvaughn says, it seems to happen in Explorer too.

**Comment by BottomleyIan** [comment] 2018-12-03 23:03
Chrome 70.0.3538.110 Jumps back to where you started dragging from, not just the top. Also happens eventually if you move the mouse to the right.

Firefox 63.0.3 (32-bit) If you start dragging directly down its fine, but drag off to the left and it will jump back

**Comment by JeffBaumgardt** [comment] 2018-12-03 23:09
It is a common windows behavior as I've replicated this in non-browser applications as well as browsers.

**Comment by Agedjus** [comment] 2018-12-03 23:10
I was playing a bit, looks like the shared behavior between browsers is jumping back to the initial position if you drag the mouse far enough through the other axis direction. Firefox, Edge, IE, Chrome and w10 system. Is it a default behavior in general or just because of windows?

Dragging in the same axis... it happens to Chrome and w10 explorer, other browsers works fine, even IE

**Comment by bvaughn** [comment] 2018-12-03 23:12
Thanks so much for the added context folks. I'm not sure this is something I can reasonably fix– if the browser is sending _valid_ (e.g. between 0 and max offset) but "incorrect" offsets.

**Comment by bvaughn** [comment] 2018-12-03 23:43
Thanks again for all of the input everyone!

After looking at this a bit closer, I think I'm going to close this issue as "won't fix" because (1) it seems to be widespread on Windows and (2) I don't think there's a reasonable way for me to detect and work around it.

Cheers!

**Closed by bvaughn** 2018-12-03 23:43 UTC
Labels: bug, needs info
