### ISSUE TITLE
The size of each row in the VariableSizeList is not updated in real time

### ISSUE THREAD

**Issue by cyulin** [bvaughn/react-window#223] opened 2019-04-26 17:41 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

there was a list with a heading line height of 60px and a content line height of 30px. When the number of rows changed, the height of each line did not change.
I found that the reason was that the itemSize function was not executed when row was updated.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/38kr7prwp5)

### Steps to reproduce
...

### What is expected?
Because the number of rows is dynamic, so the height of each row is not fixed, I hope itemSize can be executed when the row is updated.

### What is actually happening?
Except that the first rendering is correct, there is no corresponding change in the height of each row when the number of rows changes later.

| Environment | Info |
|---|---|
| react-window | 1.8.1 |
| React | 16.8.6 |
| System | macOs |
| Browser | chrome 73 |

---

**Comment by bvaughn** [comment] 2019-04-26 17:46
I appreciate that you searched the issues before filing this issue (although I'm not sure why you linked to [ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)?)

That being said, this looks like a duplicate of #199 . Check out [my answer there](https://github.com/bvaughn/react-window/issues/199#issuecomment-479957451).

**Closed by bvaughn** 2019-04-26 17:46 UTC
