### ISSUE TITLE
Re-creating the entire body/row nodes on data change

### ISSUE THREAD

**Issue by DDinenno** [bvaughn/react-window#308] opened 2019-08-13 15:33 UTC
I'm having an issue caused by this component **re-creating** the entire body when the data changes even though the scroll position is the same. I would think given this condition, React's reconciliation algorithm would skip over the `FixedSizeList Body/rows` and just append the innerHtml of the cell with the new value (This would be the ideal for my useCase, but maybe not for everyones).  If I generated a list by mapping over rows, if the data changed react would append the changes to the cell without **destroying/re-creating everything**.

 I wonder if something could be done about this, I could even take a look at your src, but diving in would take some time to understand the internal flow.

**Comment by bvaughn** [comment] 2019-08-13 15:37
Share your cod and I'll take a look. Issues like this that don't include any example code can't be acted on though, so I'm going to close it for now.

**Closed by bvaughn** 2019-08-13 15:37 UTC

**Comment by DDinenno** [comment] 2019-08-13 17:34
Sure thing, here's a sandbox [https://codesandbox.io/s/react-window-example-uhits](url)

I think it's pretty simple to follow ,  Lemme know if you need any more context.

Thanks for legendary response time btw 👍

**Comment by bvaughn** [comment] 2019-08-13 17:59
Console warnings seem important:
![Screen Shot 2019-08-13 at 10 56 57 AM](https://user-images.githubusercontent.com/29597/62965064-17f45a00-bdb9-11e9-8156-97044f09e4fc.png)

Inline render function is probably the cause of the unexpected (deep) re-renders:
![Screen Shot 2019-08-13 at 10 57 37 AM](https://user-images.githubusercontent.com/29597/62965105-35c1bf00-bdb9-11e9-91d2-9e4cc90136ff.png)

Inline item renderers incur a high cost. Because their "type" (the function definition) gets recreated each time the parent component renders, React deeply unmounts and remounts their rendered tree.

This is why all of the docs examples avoid showing inline functions and it's why the `itemData` API exists: https://react-window.now.sh/#/examples/list/memoized-list-items

This is something I plan to change in version 2 (see #302)

**Comment by DDinenno** [comment] 2019-08-13 20:18
Yep that did it.  

I actually was memoizing the rows in my actual implementation, but I guess improperly since I was using Inline functions and not using the itemData( I didn't think it was necessary at the time).  

Great history lesson on inline-functions.  I'm gonna stay away from those as much as possible.

Thanks a bunch! you don't know how much this helped me out and sorry for wasting your time, it was mostly ignorance on my part.  I took a look at your future changes and I'm hyped to see them in action.  Good luck with everything, this is such a helpful plugin for react ecosystem!

**Comment by bvaughn** [comment] 2019-08-13 22:01
Glad you got it sorted out :)
