### ISSUE TITLE
Differences from react-virtualized?

### ISSUE THREAD

**Issue by bhovhannes** [bvaughn/react-window#37] opened 2018-08-10 12:15 UTC
Hi,

I am just curious how is this different from react-virtualized?
Are there any conceptual differences?

Thanks!

**Comment by nihgwu** [comment] 2018-08-10 12:35
#36 
Please search before fire an issue, also I don't think Issues is the QA place

**Comment by luisbelloch** [comment] 2018-08-10 12:37
Also, if possible, it would be great to know what's the future plan for both projects. Would react virtualize deprecate part of the functionality in favour of react window? Or spin-off some parts of it as separated project?

Both projects are awesome, thanks for putting hard work on them! 😊

**Comment by TrySound** [comment] 2018-08-10 14:36
@luisbelloch virtualized has a lot of functionality which won't be implemented in react-window, so both projects will exist independently. Maybe somebody will move some optimisations to from this project to virtualized.

**Comment by bvaughn** [comment] 2018-08-10 14:52
Duplicate of #36 and #29 😄

@TrySound's answer is correct about the future plans.

**Closed by bvaughn** 2018-08-10 14:52 UTC
Labels: duplicate, question

**Comment by luisbelloch** [comment] 2018-08-10 22:01
thanks for the info! 😊

**Comment by kpennell** [comment] 2018-11-03 15:01
@bvaughn thanks for commenting here
