### ISSUE TITLE
All items re-mount on list change

### ISSUE THREAD

**Issue by ryanmcclure4** [bvaughn/react-window#413] opened 2020-02-04 19:42 UTC
I have an issue that seems identical to [this](https://github.com/bvaughn/react-window/issues/186). Each time one of the items in my list is modified, added, or removed, itemData changes. This results in all previously rendered items being re-mounted (not just re-rendered). My code is essentially identical to the examples in terms of form (data and list item differ, but the project is structured the same).

Conceptually, using memoize and React.memo should only prevent re-renders of currently mounted items. Thus, neither of those should have an effect on whether components are re-mounted. What other variables that are factored into the list's decision of whether to re-mount the items? I'm converting this from a project that used to render all items in a list, in which case the items are _not_ re-mounted. So the only difference in this case is the virtual list. I've been stuck on this for a while and feel like I'm missing something...

**Comment by pgostovic** [comment] 2020-03-11 20:51
I'd love to see this issue get some love. I've got a FixedSizeList with items that contain controlled text inputs such that the input's onChange affects some state outside of the FixedSizeList component. Every text input key press updates the state and triggers a re-render of the List; nothing out of the ordinary, just typical React controlled inputs. But because of the unmount/remount, the text input loses focus immediately. There's no scrolling going on here. Here's a trivial one-item example:

```ts
const ListTest: FC = () => {
  const [value, setValue] = useState('')

  return (
    <FixedSizeList height={150} itemCount={1} itemSize={35} width={300}>
      {({ style }) => (
        <input
          type="text"
          style={style}
          value={value}
          onChange={event => setValue(event.currentTarget.value)}
        />
      )}
    </FixedSizeList>
  )
}
```

Surely, only re-rendering should happen in this case and not fully unmounting and remounting. Any ideas?

**Comment by bvaughn** [comment] 2020-03-11 21:01
What you're asking about is slightly different, @pgostovic, and seems like a duplicate of #420.

Don't define your item renderer inline. It will get recreated each time the parent component re-renders which will mess with text selection apparently.

**Comment by pgostovic** [comment] 2020-03-11 22:30
Oh man that totally works -- I feel kind of stupid now 😄. Thanks @bvaughn!

**Comment by bvaughn** [comment] 2020-03-11 23:08
No worries. It's a common mistake. So much so that I plan to change the API for v2 (if I ever finish v2) so that the way you defined it above would not cause this problem.

**Comment by VitaminCtea** [comment] 2020-05-29 02:51
@bvaughn My situation is similar to that of the landlord. I use event delegation here to click each list element to produce some effects! However, after scrolling, it is necessary to monitor the value from Redux to judge something. Because the parent component listens, and then distributes it to the child component, it will render again. This problem is that the list item in the current viewport is missing, but the DOM is still there. When scrolling in the blank area again, the list item will appear, but it is not the scrolling item before the blank! I want to listen to the changed values so as to make some interaction effects. If I listen to the values, I have to trigger re rendering again, resulting in incorrect list items. How to solve it?

**Comment by b52** [comment] 2020-11-05 07:33
@ryanmcclure4 Did you find a solution for it? I'm facing the same issue and really prevents me from providing a snappy experience.

@bvaughn Thoughts?

**Comment by ryanmcclure4** [comment] 2020-11-05 14:49
@b52 I didn't. I ended up implementing a non-virtual list that just paginates and adds more once you scroll to the bottom. Not as nice of a solution as virtual list would be, but it works.

**Comment by yingfangdu** [comment] 2020-12-18 21:40
@bvaughn hi, do you have any plan for this issue? Our product faces the same issue that any change in a node will cause all nodes in a tree get unmount and remount. This will cause bad accessibility issue that we can truly focus on a node.

**Comment by YvetteLau** [comment] 2021-01-10 02:35
@bvaughn  Hi, do you have any plan for this issue? My product faces the same issue that any change in a node will cause all nodes in a tree get unmount and remount.

**Comment by Torvin** [comment] 2021-01-12 03:12
This happens because `react-window` treats `children` as a component which I believe is an anti-pattern for render-props as there are only a very limited number of cases where you want to pass a component. Most of the time you want to instead use an arrow function to pass additional props to your component from the parent closure.

The fix for this issue is really simple: just replace `React.createElement(children, props)` with direct `children(props)`. Unfortunately it would be a breaking change: some existing code would rely on the fact that the passed function is a component and would do something like `useState` inside.

@bvaughn as a quick fix before your v2 is out, can we opt out of this behaviour with a switch maybe? introduce `noComponent` prop to all the lists and pass it into `createListComponent()`:
```diff
--- a/src/createListComponent.js
+++ b/src/createListComponent.js
@@ -145,6 +145,7 @@ export default function createListComponent({
   initInstanceProps,
   shouldResetStyleCacheOnItemSizeChange,
   validateProps,
+  noComponent
 }: {|
   getItemOffset: GetItemOffset,
   getEstimatedTotalSize: GetEstimatedTotalSize,
@@ -321,15 +322,15 @@ export default function createListComponent({
       const items = [];
       if (itemCount > 0) {
         for (let index = startIndex; index <= stopIndex; index++) {
-          items.push(
-            createElement(children, {
-              data: itemData,
-              key: itemKey(index, itemData),
-              index,
-              isScrolling: useIsScrolling ? isScrolling : undefined,
-              style: this._getItemStyle(index),
-            })
-          );
+          const props = {
+            data: itemData,
+            key: itemKey(index, itemData),
+            index,
+            isScrolling: useIsScrolling ? isScrolling : undefined,
+            style: this._getItemStyle(index),
+          }
+
+          items.push(noComponent ? children(props) : createElement(children, props));
         }
       }
```

**Comment by DaleSalcedo** [comment] 2021-02-17 02:25
Does anyone know if react-virtualized has this issue as well? I'm having the same issue as OP which was a bit frustrating and it doesn't seem like it's being addressed by any of the maintainers

**Comment by mbret** [comment] 2021-03-30 13:07
I was hitting my head around the whole evening trying to understand why everything keeps re-rendering until i find this thread which explains exactly my problem. I want to point out that this problem is specifically visible when you have image inside the list. The unmount-mount will cause flickering issue whenever a single prop change for the list.

**Comment by ZYSzys** [comment] 2021-03-31 07:22
I've created a [demo](https://codesandbox.io/s/stupefied-voice-yrqwh) showed this re-mount behavior based on memorized-list example, you could see multiple(seven times) `memo` logs in the console when click one of the items, which means all items got rerendered, it's indeed terrible, even worse when we have avatars in the list.

@bvaughn Wondering when could this be fixed ?

**Comment by Torvin** [comment] 2021-03-31 08:02
@ZYSzys not sure what you are trying to do here. I replaced `FixedSizeList` with a usual `map` and got the same result https://codesandbox.io/s/vigorous-archimedes-cvv1c?file=/index.js

I don't think your issue lies within `react-window`

**Comment by numanash** [comment] 2021-04-23 11:11
I'm also facing the re-rendering issue I have tried memo, created separate rows component approach nothing works for me.

https://user-images.githubusercontent.com/48905195/115861068-c46e5680-a44b-11eb-8c77-985b1da3d2ac.mp4

I have an array of objects which I am passing to renders the list. Now I have to select an item for the cart to proceed with checkout whenever I select the item it re-renders the whole list which is not good.

`
array = [{item:'abc'},{item:'def'},....];
obj={abc:{
isChecked:true
},def:{
isChecked:true
},...} 
`

So what I am doing is onChange handler of input it adds a new object in obj if the item already exists it just change it's value, and I used that value to check if the item is checked or not
like
`
checked={obj[map.item]?obj[map.item]:false}
`
where checked is an attribute of the input element. 

@bvaughn 
if you have any solution to fix it, It will be really helpful for me. thanks

**Comment by w01fgang** [comment] 2021-05-26 08:59
For me worked this example https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335
The key is `Don't define your item renderer inline.`

**Comment by wasitshafi** [comment] 2021-07-05 16:00
> I was hitting my head around the whole evening trying to understand why everything keeps re-rendering until i find this thread which explains exactly my problem. I want to point out that this problem is specifically visible when you have image inside the list. The unmount-mount will cause flickering issue whenever a single prop change for the list.

@mbret i am also facing the same problem of image flickering in a list,  just wanted to know have you fixed the issue by some alternate soltuions.  I would appreciate a reply at your earliest convenience

**Comment by Karpengold** [comment] 2021-08-02 14:43
When I change state of component where List is provided, all visible items are unmounting and remounting again. Is this a bug or there is a workaround to fix this behaviour? I don't use inline function definition.

**Comment by w01fgang** [comment] 2021-08-02 19:48
@Karpengold do you have your items renderer inline?
It should be as a component like [here](https://codesandbox.io/s/react-window-5yzbr) from [this](https://github.com/bvaughn/react-window/issues/420#issuecomment-585813335) comment

**Comment by Karpengold** [comment] 2021-08-03 09:02
@w01fgang ItemRenderer is defined inside component in my case, but using useCallback hook. Could it be the main point of the issue?

**Comment by ynnelson** [comment] 2021-09-12 02:54
I am having the same issue where despite using `memoize`, not having the itemRenderer inline and using the `ItemKey` the slightest update to the states is causing all the rows to unmount and mount back up. It's creating quite a headache for me because I have a setInterval being triggered on Mount for each that gets essentially reset every mount and unmounting...

Any other ideas on how to mitigate for that?

**Comment by w01fgang** [comment] 2021-09-12 03:07
@Karpengold sorry for the late response, but yes, this is the issue. Must be a separate component defined from outside.

@ynnelson, you must define the renderer function outside of the component where you use it. It doesn't work with useCallback or useMemo or anything else.

**Comment by ynnelson** [comment] 2021-09-12 03:11
I think i did that ( see below) what am I missing/doing wrong?

```js
import React, { memo, useCallback, useEffect, useState, useMemo } from 'react';
import { useDispatch, useSelector } from 'react-redux';

// EXTERNAL UTILS LIBRAIRIES
import memoize from 'memoize-one';

// EXTERNAL COMPONENT LIBRARIES
import { VariableSizeList as List, areEqual } from 'react-window';
import AutoSizer from 'react-virtualized-auto-sizer';
import { Scrollbars } from 'react-custom-scrollbars';

// INTERNATIONALIZATION
import { BsInbox } from 'react-icons/bs';
import { Filter2, Swap } from 'react-iconly';
import i18n from '../../../../i18n/i18n';

// ICONSET ICONS

// REDUX ACTIONS

// SELECTORS
import { selectAllFolders, activeFolderId } from '../../../selectors/mail';

// TS TYPES
import {
  MailMessageType,
  FolderType,
  MailboxType,
  MailType
} from '../../../reducers/types';

// COMPONENTS IMPORTS
import MessagePreview from './MessagePreview/MessagePreview';
import MessagePreviewLoading from './MessagePreviewLoading';

// CSS STYLE IMPORTS
import styles from './MessageList.less';

type Props = {
  loading: boolean;
  onMsgClick: (message: MailMessageType, index: number) => Promise<void>;
  onDropResult: (item: any, dropResult: any) => Promise<void>;
};

const Row = memo(({ data, index, style }) => {
  const { messages, onMsgClick, onDropResult } = data;
  const msgId = messages.allIds[index];

  return (
    <MessagePreview
      index={index}
      message={messages.byId[msgId]}
      onMsgClick={onMsgClick}
      onDropResult={onDropResult}
      previewStyle={style}
    />
  );
});
Row.displayName = 'Row';

const createItemData = memoize((messages, onMsgClick, onDropResult) => ({
  messages,
  onMsgClick,
  onDropResult
}));

export default function MessageList(props: Props) {
  const { onMsgClick, loading, onDropResult } = props;

  const messages = useSelector(state => state.mail.messages);
  const folders = useSelector(selectAllFolders);
  const currentFolderId = useSelector(activeFolderId);

  const [listRef, setListRef] = useState();

  const itemData = createItemData(messages, onMsgClick, onDropResult);

  const itemKey = (index, data) => {
    const msgId = data.messages.allIds[index];
    return data.messages.byId[msgId].id;
  };

  useEffect(() => {
    setListRef(React.createRef());
  }, []);

  const CustomScrollbars = ({ onScroll, forwardedRef, style, children }) => {
    const refSetter = useCallback(scrollbarsRef => {
      if (scrollbarsRef) {
        if (listRef && listRef.current && listRef.current.state) {
          scrollbarsRef.scrollTop(listRef.current.state.scrollOffset);
          forwardedRef(scrollbarsRef.view);
        }
      } else {
        forwardedRef(null);
      }
    }, []);

    return (
      <Scrollbars
        ref={refSetter}
        onScroll={onScroll}
        style={{ ...style, overflow: 'hidden' }}
        hideTracksWhenNotNeeded
        autoHide
      >
        {children}
      </Scrollbars>
    );
  };

  const CustomScrollbarsVirtualList = React.forwardRef((props, ref) => (
    <CustomScrollbars {...props} forwardedRef={ref} />
  ));

  return (
    <div className="flex-1 flex w-full flex-col rounded-t-lg bg-white mr-2 border border-gray-200 shadow">
      <div className="h-10 w-full text-lg font-semibold justify-center py-2 pl-4 pr-4 mb-2 text-gray-600 flex flex-row justify-between">
        <div className="flex-1 select-none">
          {(folders.byId[currentFolderId] &&
            folders.byId[currentFolderId].name) ||
            ''}
          <div className="h-0.5 w-6 rounded-lg bg-gradient-to-r from-purple-700 to-purple-500 " />
        </div>
        <div className="items-end flex">
          <Swap
            set="broken"
            size="small"
            className="mr-2"
            style={{ cursor: 'pointer' }}
          />
          <Filter2 set="broken" size="small" style={{ cursor: 'pointer' }} />
        </div>
      </div>
      {messages.allIds.length > 0 && (
        <div className="flex-1 flex w-full">
          <AutoSizer>
            {({ height, width }) => (
              <List
                ref={listRef || null}
                className="List"
                height={height}
                itemKey={itemKey}
                itemCount={messages.allIds.length}
                itemData={itemData}
                itemSize={() => 74}
                width={width}
                outerElementType={listRef ? CustomScrollbarsVirtualList : null}
              >
                {Row}
              </List>
            )}
          </AutoSizer>
        </div>
      )}

      {!messages.allIds.length && (
        <div className="select-none">
          <div className="flex justify-center mt-12 text-7xl">
            <BsInbox className="opacity-20 w-16 h-16" />
          </div>
          <div className="flex justify-center mt-2">
            <div className="text-gray-400 tracking-wide">No Messages</div>
          </div>
        </div>
      )}
    </div>
  );
}

```

**Comment by w01fgang** [comment] 2021-09-13 06:24
@ynnelson did you try to remove `memo` from the renderer function?
"const Row = ~memo(~({ data, index, style }) => {"

**Comment by ynnelson** [comment] 2021-09-14 01:58
@w01fgang yeah I tried that to no avail... I have tried a couple of work around but so far no viable alternative.

**Comment by ynnelson** [comment] 2021-09-15 14:04
We found the solution and it was actually the outerElementType that was causing the constant mounting and unmounting. It's working great now.

**Comment by seanpkent** [comment] 2021-09-29 00:08
@ynnelson Can you share your solution in more detail?

**Comment by agupta1989** [comment] 2021-10-05 10:18
> We found the solution and it was actually the outerElementType that was causing the constant mounting and unmounting. It's working great now.

What was the solution ? @ynnelson

**Comment by ynnelson** [comment] 2021-10-05 12:03
@seanpkent @agupta1989 in our case we got rid of the outerElementProp being passed and went back to de default scrollbar. The issue was that element was constantly being remounted and was causing the whole list to follow suit.

**Comment by agupta1989** [comment] 2021-10-05 14:10
Thanks @ynnelson for replying.

> @seanpkent @agupta1989 in our case we got rid of the outerElementProp being passed and went back to de default scrollbar. The issue was that element was constantly being remounted and was causing the whole list to follow suit.

Looking at the code, it seems there is no way to avoid the outerElementType prop.
![image](https://user-images.githubusercontent.com/3787965/136039895-d68d62c5-5c5d-423a-ae21-4ba8cce32e52.png)

How did you manage to get rid of the outerElement ? Could you please share some code snippet ? Thanks !

**Comment by ynnelson** [comment] 2021-10-05 14:26
```jsx
<List
    ref={ref}
    onItemsRendered={onItemsRendered}
    className="List"
    height={height}
    itemKey={itemKey}
    itemCount={messages.allIds.length}
    itemData={itemData}
    itemSize={() => 74}
    width={width}
  >
    {Row}
  </List>
```

the outerElement is an optional prop, if not present it'll default to 'div'. You are misinterpreting the code above. This says:  `outerElementType | (OR) outerTagName | (OR) 'div'`

**Comment by agupta1989** [comment] 2021-10-05 14:34
> ```js
> <List
>     ref={ref}
>     onItemsRendered={onItemsRendered}
>     className="List"
>     height={height}
>     itemKey={itemKey}
>     itemCount={messages.allIds.length}
>     itemData={itemData}
>     itemSize={() => 74}
>     width={width}
>   >
>     {Row}
>   </List>
> ```
> 
> the outerElement is an optional prop, if not present it'll default to 'div'. You are misinterpreting the code above. This says: `outerElementType | (OR) outerTagName | (OR) 'div'`

correct.. what I didn't understand was the line where you said you got rid of outerElement. 
> we got rid of the outerElementProp being passed and went back to de default scrollbar

**Comment by ynnelson** [comment] 2021-10-05 14:37
I am no longer passing a custom element as the outerElementType aka it's no longer a set prop on my List

**Comment by agupta1989** [comment] 2021-10-06 05:12
> I am no longer passing a custom element as the outerElementType aka it's no longer a set prop on my List

Ok... Yeah I am also doing the same but re-rendering happens all the time. but anyway thanks for giving your time. I appreciate it.

**Comment by ynnelson** [comment] 2021-10-06 11:56
@agupta1989 if you post you code here I can try and take a look. What you want to try and pinpoint is what is causing your state to be changed, you likely have something in your state that is constantly updating the state which is causing the mount and unmount loop. The React Developer tool was very useful in seeing that, we also used a bunch of useEffect functions to zero in on what part of the state was updating. 

```js
useEffect({
console.log('var I am testing', myvar);
}, [myvar])
```
The above would get triggered any time a change is observed in that specific variable. That way we end up finding a few things that were constantly updating other places in our code, most of the issues there we due to an improperly coded selector.

**Comment by Snaptags** [comment] 2021-10-13 14:11
Had similar problems when trying to implement an inline edit mode for a table. After trying to find a workaround longer than I should have, I solved all issues by using React Virtual https://react-virtual.tanstack.com/ instead.

**Comment by mmarzullotv** [comment] 2022-06-06 15:13
Guys, i'm pretty desperate. I'm applying accessibility to the app and i move through the items using the arrow keys in the keyboard, but once i reach a certain point, focus is completely lost, hence, i can't keep moving.

I updated this example https://codesandbox.io/s/nifty-shadow-rsynso?file=/src/App.js

As you can see, focus on any input in the list, and scroll a bit down or up. You'll notice the input is longer focusing in there.

Also, in the demo there, the render item isn't being declared on the parent nor inline and still happens. 

Any help would be very appreciated.

**Comment by vdh** [comment] 2022-06-10 00:32
@mmarzullotv The only workaround I managed to find was using the React Context API to pass any relevant child props via a context, which bypasses any re-rendering in `react-window` and only triggers re-rendering in the child components instead.

**Comment by tjx666** [comment] 2024-06-13 18:28
Can't extract the render props easily because it's the closure:

```javascript
<AutoSizer
  style={{
    minHeight: '100vh',
  }}
>
  {({ height, width }) => {
    return (
      <InfiniteLoader
        isItemLoaded={isItemLoaded}
        itemCount={itemCount}
        loadMoreItems={loadMoreItems}
        threshold={5}
      >
        {({ onItemsRendered, ref }) => (
          <List
            width={width}
            height={height}
            onItemsRendered={onItemsRendered}
            ref={ref}
            itemCount={itemCount}
            itemSize={
              sliderValue > 4
                ? ROW_HEIGHT
                : isMobile
                  ? ROW_HEIGHT
                  : sliderValue > 2
                    ? ROW_HEIGHT * 2
                    : ROW_HEIGHT * 3
            }
          >
            {(props) => {
              return renderRow({ ...props, width });
            }}
          </List>
        )}
      </InfiniteLoader>
    );
  }}
</AutoSizer>
```

**Comment by sravaniPrism** [comment] 2024-06-27 08:26
I am also facing same situation https://github.com/bvaughn/react-window/issues/769

**Comment by roux1max** [comment] 2024-07-03 06:53
Hey guys, run into the same problem trying to integrate a Dnd feature within react-window and just fixed my render problem by changing my inline components to explicit ones. Did that for the list children AND the `outerElementType` and it just worked.

To pass down additional props to the children component I just used the `itemData` prop of the list as it seemed the bests fit for me.

**Closed** 2024-08-13 19:55 UTC

**Comment by tomasamado97** [comment] 2025-01-03 16:49
I know this issue is closed but for those that come here looking for the solution, I tested and its a mix of removing the component thats being iterated from the parent component plus if you need to use your own custom props, you need to use a context to avoid passing them down as props.

Example: (Mind you, not the best code)

```
List.js:
<VirtualizedContextProvider
  // your props here
>
    <Grid
        columnCount={numColumns}
        columnWidth={getColumnWidth}
        height={CARD_HEIGHT + GAP}
        rowCount={Math.ceil(items.length / numColumns)}
        rowHeight={CARD_HEIGHT + GAP}
        width={innerWidth}
        itemData={items}
    >
        {VirtualizedCard}
    </Grid>
</VirtualizedContextProvider>
```

```
VirtualizedCard.js:
import React, { useContext } from "react"
import ProductCard from "../../ProductCard";
import { VirtualizedContext } from "./VirtualizedContext";

const VirtualizedCard = ({ data, columnIndex, rowIndex, style }) => {
  // props you need come from the context
    const { exampleProp1 } = useContext(VirtualizedContext);

    return (
        // Card JSX
    );
};

export default VirtualizedCard;
```

```
VirtualizedContext.js:
import React, { createContext } from 'react'

export const VirtualizedContext = createContext({
    props or state you might need...
})

const VirtualizedContextProvider = ({ children, ...props }) => {

    const context = {
        props or state you might need...
    }

    return (
        <VirtualizedContext.Provider value={context}>
            {children}
        </VirtualizedContext.Provider>
    )
};

export default VirtualizedContextProvider;

```

If you need any help, hit me up I might be able to take a look and help out.
